### PR TITLE
Update to new rails validators

### PR DESCRIPTION
**Pull request by Br3nda**

### CODE REVIEW

**Comment by Br3nda** [comment]
Travis CI won't pass until #299 is merged

**Comment by RickCarlino** [comment]
:tada: Thanks for catching these- we just upgraded to Rails 5 last week, so there is still quite a bit of old API usage floating around.

Will merge once this re-started build passes.

**Comment by RickCarlino** [comment]
Hmmm. Looks like Travis isn't actually creating the database tables for this run, causing some `PG::UndefinedTable` errors.

**Comment by Br3nda** [comment]
I'll merge master into this pr and that should fix it

**Comment by Br3nda** [comment]
It could be more graceful - but in the meantime, how about we add pulling that file in the travis script?

**Comment by Br3nda** [comment]
like this:
```before_script:
  - cp config/database.travis.yml config/database.yml
  - ./install_frontend.sh
  - bundle exec rake db:create db:migrate```

**Comment by RickCarlino** [comment]
@Br3nda Cool! Looks good.

**Pull request merged**
