### PR TITLE
Indentation, trailing space, and blank line clean up

### PR DESCRIPTION
**Pull request by Br3nda**
I was finding inconsistent indentation as I read through the code - so i ran rubocop over it to clean up the whitespace.

### CODE REVIEW

**Comment by Br3nda** [comment]
Okay, stopping before i get carried away.

**Comment by Br3nda** [comment]
Radio silence......

**Comment by RickCarlino** [comment]
@Br3nda This branch has conflicts that must be resolved. The more I think about it though, the more I think it might be better to just update the `rubcop.yml` file so that we can introduce consistent formatting incrementally instead of changing the codebase all at once. I used to have Hound setup for this project to do just that, but it looks like it has not been barking as of late.

**Comment by Br3nda** [comment]
@RickCarlino would you like more PRs? I was a bit dismayed by this PR
I can see bugs but not sure you're accepting outside PRs or not.

**Comment by RickCarlino** [comment]
@Br3nda Sure.

**Pull request closed without merging**
